language: rust
rust:
- stable
sudo: false
script:
- make doc
after_success: |
  git config user.name "Igor.Shaposhnik"
  git config user.email "shaposhnikigor95@bk.ru"
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $(uname -s) = Linux ] &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${CDOC_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: GFn768YsX8U+PuK6KPEGO/OQAnR5HP2YIN0tNILw3QBEqRdYrLl0HphfXQb8F0NmD4ra5eIgKyEAvu5xNyshFkwR6LfAYnMbYbQdWjYKnWKkBg9bLW3tUBHH0uTz7SlT4BBnLwdjufUJBuMOjEX0h2ky+HiY9872Yq0upzk51RMZsAd0e3758Zqj7RXc2/e2MlpdmLQv4gOOguy0ewCeDYyTiy4chJTO26XN+/dZTQspPhkO8UoBB8NjXxzcSHRdkJux4p1tu5UobMejxKJXuVGqMbVmnjofFv4ATQZrt8/XCJJlR40+6oZxC6vCCapfC4FYdehaIBZQF23l9W3cfiiqbrhGIzJB8xOQL/IMLiK//MjXYdJv+XlbTJSS8Pp6IeVTsNCZRigxLtzxj4f9bztBS2l7h7RVPynLL/w55icIf+c6JSThWQofwLLzVwVVn2kQhx8N79Rufuojk8f+SiL+tAlBJhULFsmj8stvROzzFODPGisSQ2UQFgu6f1lhegufl5fr/CWCNGpL0A/q0nXUiVVkaBAg3cROvNXEKx5vFw/0kgNOAVRq/PflU4Vg7L31AR2s8SOMuf4+dpxueiiayOPOxFz00l/LfKFDRL+PJYZvGQhKqTB+meY2syM6ydtClHX+vJCYfPLJWxCfPYgbfLBE0+tjBKiFfSpdrYE=
os:
- linux
branches:
  only:
  - master
